name: OpenID Connect with Reusable Workflows
on:
  workflow_call:
    inputs:
      environment:
        description: Possible values are `development`, `staging`, `production`.
        required: true
        type: string
    secrets:
      AWS_REGION:
        required: true
      BUCKET_NAME:
        required: true
      ROLE_SESSION_NAME:
        required: true
      ROLE_TO_ASSUME:
        required: true
permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
jobs:
  cd-to-s3:
    name: Continuous Delivery to S3
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp ./index.html s3://${{ secrets.BUCKET_NAME }}/
